image: docker:latest

stages:
  - build
  - deploy

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" --build-arg SPACE_ID=$SPACE_ID --build-arg SPACE_API_KEY=$SPACE_API_KEY --build-arg GOOGLE_TAGMANAGER_ID=$GOOGLE_TAGMANAGER_ID .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  only:
    - master

deploy_development:
  stage: deploy
  type: deploy
  environment:
    name: development
    url: http://mozilla-labs.ramotion.com/
  image: registry.gitlab.com/ramotion/rancher-cli-k8s
  script:
    - rancher login "$RANCHER_SERVER_URL" -t "$RANCHER_API_TOKEN" --context "$RANCHER_API_CONTEXT"
    - rancher kubectl --namespace=mozilla-labs-development patch deployment landing --type=strategic -p '{"spec":{"template":{"spec":{"containers":[{"name":"'landing'","image":"'$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA'"}]}}}}'
  only:
    - master
